services:
    mc-server:
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        restart: on-failure
        ports:
            - '8888:25565'
        environment:
            EULA: 'TRUE'
            SERVER_NAME: 'Peaceful World'
            LEVEL_TYPE: 'flat'
            MAX_PLAYERS: '5'
            MAX_WORLD_SIZE: '1000'
            DIFFICULTY: 'peaceful'
        volumes:
            - local_data:/data

volumes:
    local_data:
