services:
    mc-server:
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        restart: on-failure
        ports:
            - '8888:25565'
        environment:
            EULA: 'TRUE'
            SERVER_NAME: '${SERVER_NAME}'
            LEVEL_TYPE: '${LEVEL_TYPE}'
            MAX_PLAYERS: '${MAX_PLAYERS}'
            MAX_WORLD_SIZE: '${MAX_WORLD_SIZE}'
            DIFFICULTY: '${DIFFICULTY}'
        volumes:
            - local_data:/data

volumes:
    local_data:
